### ISSUE TITLE
Find US business ratings.

### ISSUE THREAD

**Issue by sanderyang** [sanderyang/Safe-Home-Finder#3]

**Comment by Sonjongkook** [comment]
I am a little confused about what we should find here. Do You mean which place is a good place to start a business or get a job?

**Comment by sanderyang** [comment]
For this issue, I would like to find some type of dataset that can tell us the customer ratings of businesses. Such as, x restaurant has a 4.5 star rating out of 2000+ customer reviews. This isn't just for restaurants, but for any businesses around the specific area (grocery stores, car insurance companies, etc).
